name: Build DMD FUSE Standalone APK
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build Android Standalone APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Project and Build
        run: |
          cordova create build_folder com.pincab.dmdfusestandalone "DMD FUSE Standalone"
          rm -rf build_folder/www
          cp -r www build_folder/www
          
          # COPIE DU DOSSIER SERVEUR NODE.JS EMBARQUÉ ET DU LOGO
          if [ -d "nodejs-project" ]; then
            cp -r nodejs-project build_folder/nodejs-project
          fi
          
          if [ -f "logo.png" ]; then
            cp logo.png build_folder/logo.png
          fi
          
          cd build_folder
          
          # Configuration du config.xml embarquant Node.js
          echo '<?xml version="1.0" encoding="utf-8"?>
          <widget id="com.pincab.dmdfusestandalone" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android">
              <name>DMD FUSE Standalone</name>
              <content src="index.html" />
              <access origin="*" />
              <allow-navigation href="ws://*/*" />
              <allow-navigation href="http://*/*" />
              <allow-intent href="http://*/*" />
              <preference name="Orientation" value="landscape" />
              <preference name="Fullscreen" value="true" />
              
              <preference name="scheme" value="http" />
              <preference name="hostname" value="localhost" />

              <platform name="android">
                  <edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
                      <application android:usesCleartextTraffic="true" />
                  </edit-config>
                  <icon src="logo.png" />
              </platform>
          </widget>' > config.xml

          cordova platform add android
          
          # Plugin permettant l'exécution de Node.js en tâche de fond native sur Android
          cordova plugin add nodejs-mobile-cordova
          
          cordova build android

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: DMD-FUSE-Standalone-Application
          path: build_folder/platforms/android/app/build/outputs/apk/debug/app-debug.apk
